"""empty message

Revision ID: 67c6d60787a7
Revises: 148f31e2c5fb
Create Date: 2019-06-09 20:19:19.727660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c6d60787a7'
down_revision = '148f31e2c5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_item', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('shopping_item', sa.Column('shopping_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_item', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'shopping_item', 'shopping_list', ['shopping_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_item', type_='foreignkey')
    op.drop_constraint(None, 'shopping_item', type_='foreignkey')
    op.drop_column('shopping_item', 'shopping_list_id')
    op.drop_column('shopping_item', 'product_id')
    # ### end Alembic commands ###
